(()=>{
 const VERSION='1.7.2',TIMEOUT=4500,RADII=[1000,3000,8000,16000,32000],BEARINGS=[0,60,120,180,240,300],BYPASS=[140,220,320,480];
 const block=c=>c.routeBlocking!==false&&!['red-light','speed','traffic'].includes(c.category);
 const rad=c=>/flock|alpr|lpr|license plate|plate reader/i.test(`${c.label||''} ${c.type||''} ${c.source||''}`)?35:30;
 function clear(){if(routePolyline){try{map.removeLayer(routePolyline)}catch(_){}routePolyline=null}routeSteps=[];currentStepIdx=0;document.getElementById('turn-hud')?.style&&(document.getElementById('turn-hud').style.display='none')}
 async function json(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
 async function routes(points,alts=true){const q=points.map(p=>`${p[1]},${p[0]}`).join(';');return (await json(`https://router.project-osrm.org/route/v1/driving/${q}?overview=full&geometries=geojson&steps=true&alternatives=${alts?'true':'false'}`)).routes||[]}
 function dist(lat,lng,a,b){const mx=111320*Math.cos(lat*Math.PI/180),my=110540,ax=(a[0]-lng)*mx,ay=(a[1]-lat)*my,bx=(b[0]-lng)*mx,by=(b[1]-lat)*my,vx=bx-ax,vy=by-ay,n=vx*vx+vy*vy,t=Math.max(0,Math.min(1,n?-(ax*vx+ay*vy)/n:0));return Math.hypot(ax+t*vx,ay+t*vy)}
 function audit(r){const p=r?.geometry?.coordinates||[],hits=[];for(const c of (cameraLocations||[])){if(!block(c))continue;const la=+c.lat,ln=+c.lng;if(!Number.isFinite(la)||!Number.isFinite(ln))continue;let best=Infinity;for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1];if(la<Math.min(a[1],b[1])-.0007||la>Math.max(a[1],b[1])+.0007||ln<Math.min(a[0],b[0])-.0007||ln>Math.max(a[0],b[0])+.0007)continue;best=Math.min(best,dist(la,ln,a,b));if(best<=rad(c))break}if(best<=rad(c))hits.push(c)}return{hits,count:hits.length,clear:hits.length===0}}
 function dest(lat,lng,b,d){const R=6371000,q=b*Math.PI/180,p=lat*Math.PI/180,l=lng*Math.PI/180,x=d/R,p2=Math.asin(Math.sin(p)*Math.cos(x)+Math.cos(p)*Math.sin(x)*Math.cos(q)),l2=l+Math.atan2(Math.sin(q)*Math.sin(x)*Math.cos(p),Math.cos(x)-Math.sin(p)*Math.sin(p2));return[p2*180/Math.PI,((l2*180/Math.PI+540)%360)-180]}
 function bearing(a,b){const p1=a[0]*Math.PI/180,p2=b[0]*Math.PI/180,dl=(b[1]-a[1])*Math.PI/180;return(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360}
 function uniq(xs){const seen=new Set;return xs.filter(x=>{const k=`${Math.round(x.route.distance/50)}-${Math.round(x.route.duration/30)}-${x.audit.count}`;if(seen.has(k))return false;seen.add(k);return true})}
 async function bypass(item,start,end){let best=item;if(!best||best.audit.clear)return best;for(let pass=0;pass<3&&best.audit.hits.length;pass++){const cams=best.audit.hits.slice(0,3);const attempts=[];for(const c of cams){const cp=[+c.lat,+c.lng],axis=bearing(start,end);for(const d of BYPASS){for(const side of [-1,1]){const wp=dest(cp[0],cp[1],axis+side*90,d);attempts.push(routes([start,wp,end],false).then(rs=>rs.map(r=>({route:r,audit:audit(r)}))).catch(()=>[]))}}}const batches=await Promise.all(attempts);const candidates=batches.flat();if(!candidates.length)break;const next=[best,...candidates].sort((a,b)=>a.audit.count-b.audit.count||a.route.duration-b.route.duration)[0];best=next;if(best.audit.clear)break}return best}
 async function collect(start,end){const out=[];const add=async pts=>{try{for(const r of await routes(pts,true))out.push({route:r,audit:audit(r)})}catch(_){}};await add([start,end]);const m=[(start[0]+end[0])/2,(start[1]+end[1])/2];for(const rr of RADII){await Promise.all(BEARINGS.map(b=>add([start,dest(m[0],m[1],b,rr),end])));if(uniq(out).length>=12)break}let all=uniq(out);if(all.length){const low=[...all].sort((a,b)=>a.audit.count-b.audit.count||a.route.duration-b.route.duration)[0];const improved=await bypass(low,start,end);if(improved)all=uniq([...all,improved])}return all}
 function picks(all){const fastest=[...all].sort((a,b)=>a.route.duration-b.route.duration)[0];const ghost=[...all].sort((a,b)=>a.audit.count-b.audit.count||a.route.duration-b.route.duration)[0];const maxT=Math.max(...all.map(x=>x.route.duration),1),maxC=Math.max(...all.map(x=>x.audit.count),1);const balanced=[...all].sort((a,b)=>(a.route.duration/maxT*.48+a.audit.count/maxC*.52)-(b.route.duration/maxT*.48+b.audit.count/maxC*.52))[0];return[{name:'FASTEST',item:fastest},{name:'BALANCED',item:balanced},{name:'GHOST PATH',item:ghost}]}
 function draw(item){clear();const r=item.route,ll=r.geometry.coordinates.map(p=>[p[1],p[0]]);routePolyline=L.polyline(ll,{color:item.audit.clear?'#38bdf8':'#f59e0b',weight:6,dashArray:'8, 8'}).addTo(map);map.fitBounds(routePolyline.getBounds(),{padding:[60,60]});routeSteps=(r.legs||[]).flatMap(l=>l.steps||[]);if(routeSteps.length){const h=document.getElementById('turn-hud');if(h)h.style.display='flex';updateTurnHUD(routeSteps[0])}}
 function showChoices(options){document.getElementById('gl-route-choices')?.remove();const box=document.createElement('div');box.id='gl-route-choices';box.style.cssText='position:fixed;left:12px;right:12px;bottom:78px;z-index:9998;background:rgba(5,12,22,.96);border:1px solid #28445d;border-radius:16px;padding:10px;box-shadow:0 14px 35px #000a;font-family:system-ui;color:#fff';box.innerHTML='<div style="font-weight:900;font-size:12px;letter-spacing:.8px;color:#7dd3fc;margin:2px 4px 8px">CHOOSE YOUR ROUTE</div>';options.forEach(o=>{const x=o.item;if(!x)return;const b=document.createElement('button');const mins=Math.round(x.route.duration/60),miles=(x.route.distance/1609.344).toFixed(1),zero=x.audit.clear;b.style.cssText='width:100%;display:flex;justify-content:space-between;align-items:center;margin:6px 0;padding:12px;border-radius:12px;border:1px solid '+(zero?'#22c55e':'#334155')+';background:#0b1724;color:#fff;text-align:left';b.innerHTML=`<span><b>${o.name}</b><br><small>${miles} mi • ~${mins} min</small></span><span style="font-weight:900;color:${zero?'#4ade80':'#fbbf24'}">${x.audit.count} mapped camera${x.audit.count===1?'':'s'}${zero?' • ZERO EXPOSURE':''}</span>`;b.onclick=()=>{draw(x);box.remove();if(typeof showHudToast==='function')showHudToast(`${o.name} • ${x.audit.count} mapped camera${x.audit.count===1?'':'s'}`)};box.appendChild(b)});document.body.appendChild(box)}
 async function search(){const q=document.getElementById('dest-address')?.value?.trim();if(!q)return;closeSearch();clear();try{if(typeof showHudToast==='function')showHudToast('Building Fastest, Balanced & Ghost Path…');const n=await json(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`);if(!n.length)throw Error('Destination not found.');if(!Array.isArray(userCoords))throw Error('Current GPS location is not ready yet.');const start=[+userCoords[0],+userCoords[1]],end=[+n[0].lat,+n[0].lon];const all=await collect(start,end);if(!all.length)throw Error('Routing service did not return alternatives.');showChoices(picks(all))}catch(e){if(typeof showHudModal==='function')showHudModal('Route Unavailable',e.message||'Unable to calculate route.',{tone:'danger'})}}
 window.executeSearch=search;
})();