(()=>{
  const VERSION='1.6.9';
  const REQUEST_TIMEOUT_MS=4500;
  const FAST_RADII=[120,250,500,900,1600,3000,6000,12000,25000];
  const BEARINGS=[0,45,90,135,180,225,270,315];
  function key(c){return String(c.node_id||c.id||`${c.lat},${c.lng}`)}
  function blocking(c){if(c.routeBlocking===false)return false;return !['red-light','speed','traffic'].includes(c.category)}
  function radius(c){const s=`${c.label||''} ${c.type||''} ${c.source||''}`.toLowerCase();if(/long[- ]?range|falcon\s*lr/.test(s))return 50;if(/short[- ]?range|falcon\s*sr/.test(s))return 22;if(/flock|alpr|lpr|license plate|plate reader/.test(s))return 35;return 30}
  function clearRoute(){if(routePolyline){try{map.removeLayer(routePolyline)}catch(_){}routePolyline=null}routeSteps=[];currentStepIdx=0;const h=document.getElementById('turn-hud');if(h)h.style.display='none'}
  function destPoint(lat,lng,b,d){const R=6371000,q=b*Math.PI/180,p=lat*Math.PI/180,l=lng*Math.PI/180,x=d/R,p2=Math.asin(Math.sin(p)*Math.cos(x)+Math.cos(p)*Math.sin(x)*Math.cos(q)),l2=l+Math.atan2(Math.sin(q)*Math.sin(x)*Math.cos(p),Math.cos(x)-Math.sin(p)*Math.sin(p2));return[p2*180/Math.PI,((l2*180/Math.PI+540)%360)-180]}
  async function json(url,ms=REQUEST_TIMEOUT_MS){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
  async function routes(points,alts=false){const q=points.map(p=>`${p[1]},${p[0]}`).join(';');const d=await json(`https://router.project-osrm.org/route/v1/driving/${q}?overview=full&geometries=geojson&steps=true&alternatives=${alts?'true':'false'}`);return d.routes||[]}
  function segDist(lat,lng,a,b){const mx=111320*Math.cos(lat*Math.PI/180),my=110540,ax=(a[0]-lng)*mx,ay=(a[1]-lat)*my,bx=(b[0]-lng)*mx,by=(b[1]-lat)*my,vx=bx-ax,vy=by-ay,n=vx*vx+vy*vy,t=Math.max(0,Math.min(1,n?-(ax*vx+ay*vy)/n:0));return Math.hypot(ax+t*vx,ay+t*vy)}
  function audit(r){const pts=r?.geometry?.coordinates||[],hits=[];if(pts.length<2)return{clear:false,hits,nearest:0};for(const c of (cameraLocations||[])){if(!blocking(c))continue;const lat=+c.lat,lng=+c.lng;if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;let best=Infinity,idx=-1;for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];if(lat<Math.min(a[1],b[1])-.0007||lat>Math.max(a[1],b[1])+.0007||lng<Math.min(a[0],b[0])-.0007||lng>Math.max(a[0],b[0])+.0007)continue;const d=segDist(lat,lng,a,b);if(d<best){best=d;idx=i}if(best<=radius(c))break}if(best<=radius(c))hits.push({camera:c,distance:best,segmentIndex:idx})}return{clear:hits.length===0,hits,nearest:hits.length?Math.min(...hits.map(h=>h.distance)):Infinity}}
  function score(x){return x.audit.hits.length*1e9+(x.route.distance||0)}
  function best(xs){return xs.filter(Boolean).sort((a,b)=>score(a)-score(b))[0]||null}
  function toast(s){if(typeof showHudToast==='function')showHudToast(s)}
  async function batch(candidates,start,end,tested){const workers=4,out=[],queue=candidates.slice();async function work(){while(queue.length){const via=queue.shift();try{const rs=await routes([start,...via,end],false);if(rs[0]){const x={route:rs[0],audit:audit(rs[0]),via};tested.push(x);out.push(x);if(x.audit.clear)queue.length=0}}catch(_){}}}await Promise.all(Array.from({length:Math.min(workers,queue.length)},work));return out}
  function bypasses(hit){const c=hit.camera,out=[];for(const r of FAST_RADII)for(const b of BEARINGS)out.push([destPoint(+c.lat,+c.lng,b,r)]);return out}
  async function find(start,end){const tested=[];toast('Finding fastest clear Shadow Route…');let base=[];try{base=await routes([start,end],true)}catch(_){}for(const r of base){const x={route:r,audit:audit(r),via:[]};tested.push(x);if(x.audit.clear)return x}let cur=best(tested);if(!cur)return null;
    const seen=new Set();for(let round=0;round<8&&cur.audit.hits.length;round++){const hit=cur.audit.hits.find(h=>!seen.has(key(h.camera)))||cur.audit.hits[0];seen.add(key(hit.camera));toast(`Bypassing ${cur.audit.hits.length} surveillance conflict${cur.audit.hits.length===1?'':'s'}…`);const opts=await batch(bypasses(hit),start,end,tested);const clear=opts.find(x=>x.audit.clear);if(clear)return clear;const next=best(opts);if(next&&score(next)<score(cur))cur=next}
    const mid=[(start[0]+end[0])/2,(start[1]+end[1])/2],wide=[];for(const r of [40000,80000,160000,320000,600000,804672])for(const b of BEARINGS)wide.push([destPoint(mid[0],mid[1],b,r)]);toast('Trying wide detours…');const w=await batch(wide,start,end,tested);const clear=w.find(x=>x.audit.clear);return clear||best([...w,cur,...tested])
  }
  function display(item,verified){clearRoute();const r=item.route,ll=r.geometry.coordinates.map(p=>[p[1],p[0]]);routePolyline=L.polyline(ll,{color:verified?'#38bdf8':'#f59e0b',weight:6,dashArray:'8, 8'}).addTo(map);map.fitBounds(routePolyline.getBounds(),{padding:[60,60]});routeSteps=(r.legs||[]).flatMap(l=>l.steps||[]);currentStepIdx=0;if(routeSteps.length){const h=document.getElementById('turn-hud');if(h)h.style.display='flex';updateTurnHUD(routeSteps[0])}const mi=((r.distance||0)/1609.344).toFixed(1),min=Math.round((r.duration||0)/60);toast(`${verified?'ZERO-CAMERA ROUTE VERIFIED':'BEST AVAILABLE SHADOW ROUTE'} • ${mi} mi • ~${min} min${verified?'':` • ${item.audit.hits.length} mapped conflict${item.audit.hits.length===1?'':'s'}`}`)}
  async function search(){const q=document.getElementById('dest-address')?.value?.trim();if(!q)return;closeSearch();clearRoute();try{const n=await json(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`,4500);if(!n.length)throw Error('Destination not found.');if(!Array.isArray(userCoords))throw Error('Current GPS location is not ready yet.');const item=await find([+userCoords[0],+userCoords[1]],[+n[0].lat,+n[0].lon]);if(!item)throw Error('Routing service did not return a route.');display(item,item.audit.clear);if(!item.audit.clear&&typeof showHudModal==='function')showHudModal('Best Available Shadow Route',`A fully camera-free route could not be verified quickly. GhostLane loaded the best route found instead. It has ${item.audit.hits.length} mapped surveillance conflict${item.audit.hits.length===1?'':'s'}, highlighted by the camera layer.`,{tone:'warning'})}catch(e){clearRoute();if(typeof showHudModal==='function')showHudModal('Route Unavailable',e?.name==='AbortError'?'Routing service timed out. Try again.':(e.message||'Unable to calculate route.'),{tone:'danger'})}}
  window.executeSearch=search;
})();