const zlib=require('zlib');
const OKC={minLat:35.15,minLng:-97.95,maxLat:35.85,maxLng:-97.05};
const DEFLOCK_INDEX={bin:'https://tiles.dontgetflocked.com/cameras-us-hourly-index.bin',meta:'https://tiles.dontgetflocked.com/cameras-us-hourly-index.json'};
const DEFLOCK_LEGACY_SOURCES=['https://data.dontgetflocked.com/cameras.geojson.gz','https://data.dontgetflocked.com/cameras.geojson'];
const OVERPASS_ENDPOINTS=['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter','https://lz4.overpass-api.de/api/interpreter'];
const inOkc=(lat,lng)=>lat>=OKC.minLat&&lat<=OKC.maxLat&&lng>=OKC.minLng&&lng<=OKC.maxLng;
function parseHeading(v){const n=Number(v);if(Number.isFinite(n))return{heading:((n%360)+360)%360,headingKnown:true};const m={N:0,NE:45,E:90,SE:135,S:180,SW:225,W:270,NW:315},k=String(v||'').trim().toUpperCase().split(';')[0];return Object.prototype.hasOwnProperty.call(m,k)?{heading:m[k],headingKnown:true}:{heading:0,headingKnown:false}}
function blob(t={}){return[t.name,t.operator,t.brand,t.manufacturer,t['surveillance:type'],t['camera:type'],t.surveillance,t.description,t.enforcement,t.highway].filter(Boolean).join(' ').toLowerCase()}
function category(t={}){const b=blob(t),e=String(t.enforcement||'').toLowerCase(),h=String(t.highway||'').toLowerCase();if(/flock|alpr|license\s*plate|plate\s*reader|automatic\s*license|\blpr\b/.test(b))return'alpr';if(e==='traffic_signals'||/red[- ]?light/.test(b))return'red-light';if(h==='speed_camera'||e==='speed'||/\bspeed camera\b/.test(b))return'speed';if(e||/traffic enforcement|traffic camera/.test(b))return'traffic';return'surveillance'}
function labelFor(t,c){return String(t.manufacturer||t.brand||t.operator||t.name||({alpr:'ALPR / Flock Camera','red-light':'Red-Light Camera',speed:'Speed Camera',traffic:'Traffic Camera',surveillance:'Surveillance Camera'}[c])).slice(0,180)}
function typeFor(t,c){return String(t['surveillance:type']||t['camera:type']||t.surveillance||t.enforcement||({alpr:'ALPR / License Plate Reader','red-light':'Red-Light Enforcement',speed:'Speed Enforcement',traffic:'Traffic Enforcement',surveillance:'Surveillance Camera'}[c])).slice(0,180)}
function normalizeFeature(f,source='DeFlock / OpenStreetMap'){const p=f?.properties||{},co=f?.geometry?.coordinates;if(!Array.isArray(co)||co.length<2)return null;const lng=+co[0],lat=+co[1];if(!Number.isFinite(lat)||!Number.isFinite(lng)||!inOkc(lat,lng))return null;const t=p.tags||p,c=category(t),d=parseHeading(t.direction??t['camera:direction']??t.heading);return{lat,lng,id:String(p.id||t.id||`PUB-${lat.toFixed(6)}-${lng.toFixed(6)}`),heading:d.heading,headingKnown:d.headingKnown,label:labelFor(t,c),type:typeFor(t,c),category:c,routeBlocking:c==='alpr'||c==='surveillance',source,confidence:'community'}}
function parseBody(buf){let d=buf;if(buf.length>=2&&buf[0]===0x1f&&buf[1]===0x8b)d=zlib.gunzipSync(buf);return JSON.parse(d.toString('utf8'))}
async function timed(url,opt={},ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(t)}}
function parseDeflockIndex(bytes,meta={}){let buf=Buffer.from(bytes);if(buf.length>=2&&buf[0]===0x1f&&buf[1]===0x8b)buf=zlib.gunzipSync(buf);if(buf.length<16||buf.subarray(0,4).toString()!=='FHIX')throw new Error('invalid FHIX header');const version=buf.readUInt32LE(4),count=buf.readUInt32LE(8),expected=16+count*9;if(version!==1)throw new Error(`unsupported FHIX version ${version}`);if(buf.length<expected)throw new Error(`truncated FHIX body (${buf.length}/${expected})`);const latOffset=16,lngOffset=16+count*4,brandOffset=16+count*8,brands=Array.isArray(meta.brands)?meta.brands:[],nodes=[];for(let i=0;i<count;i++){const latMicro=buf.readInt32LE(latOffset+i*4),lngMicro=buf.readInt32LE(lngOffset+i*4),lat=latMicro/1e6,lng=lngMicro/1e6;if(!inOkc(lat,lng))continue;const brand=String(brands[buf.readUInt8(brandOffset+i)]||'').trim(),knownBrand=brand&&!/^unknown$/i.test(brand);nodes.push({lat,lng,id:`DEFLOCK-${latMicro}-${lngMicro}`,heading:0,headingKnown:false,label:knownBrand?brand:'ALPR / Flock Camera',type:'ALPR / License Plate Reader',category:'alpr',routeBlocking:true,source:'DeFlock Hourly / OpenStreetMap',confidence:'community'})}return nodes}
async function fetchDeflockIndex(){const headers={Accept:'application/octet-stream, application/json, */*','User-Agent':'GhostLane/1.8.0 camera-mesh'},[binResponse,metaResponse]=await Promise.all([timed(DEFLOCK_INDEX.bin,{headers},16000),timed(DEFLOCK_INDEX.meta,{headers},16000)]);if(!binResponse.ok)throw new Error(`index HTTP ${binResponse.status}`);if(!metaResponse.ok)throw new Error(`metadata HTTP ${metaResponse.status}`);const [bytes,meta]=await Promise.all([binResponse.arrayBuffer(),metaResponse.json()]),nodes=parseDeflockIndex(bytes,meta);if(!nodes.length)throw new Error('zero OKC nodes');return{nodes,source:'DeFlock Hourly / OpenStreetMap'}}
async function fetchDeflock(){const failures=[];try{return await fetchDeflockIndex()}catch(e){failures.push(`${DEFLOCK_INDEX.bin}: ${e.name==='AbortError'?'timeout':e.message}`)}for(const url of DEFLOCK_LEGACY_SOURCES){try{const r=await timed(url,{headers:{Accept:'application/json, application/geo+json, application/gzip, */*','User-Agent':'GhostLane/1.8.0 camera-mesh'}},16000);if(!r.ok)throw new Error(`HTTP ${r.status}`);const geo=parseBody(Buffer.from(await r.arrayBuffer()));const nodes=(geo.features||[]).map(f=>normalizeFeature(f)).filter(Boolean);if(nodes.length)return{nodes,source:'DeFlock Daily / OpenStreetMap'};throw new Error('zero OKC nodes')}catch(e){failures.push(`${url}: ${e.name==='AbortError'?'timeout':e.message}`)}}throw new Error(`DeFlock unavailable (${failures.join(' | ')})`)}
function query(){const b=`${OKC.minLat},${OKC.minLng},${OKC.maxLat},${OKC.maxLng}`;return`[out:json][timeout:20];(nwr["man_made"="surveillance"](${b});nwr["surveillance:type"="ALPR"](${b});nwr["highway"="speed_camera"](${b});nwr["enforcement"="traffic_signals"](${b});nwr["enforcement"="speed"](${b});nwr["enforcement"](${b}););out center tags;`}
function normOsm(e){const p=Number.isFinite(e.lat)&&Number.isFinite(e.lon)?{lat:e.lat,lng:e.lon}:e.center&&Number.isFinite(e.center.lat)&&Number.isFinite(e.center.lon)?{lat:e.center.lat,lng:e.center.lon}:null;if(!p||!inOkc(p.lat,p.lng))return null;const t=e.tags||{},c=category(t),d=parseHeading(t.direction??t['camera:direction']??t.heading);return{lat:+p.lat,lng:+p.lng,id:`OSM-${e.type}-${e.id}`,heading:d.heading,headingKnown:d.headingKnown,label:labelFor(t,c),type:typeFor(t,c),category:c,routeBlocking:c==='alpr'||c==='surveillance',source:'OpenStreetMap / Overpass',confidence:'community'}}
async function fetchOverpass(){const q=query(),failures=[];for(const ep of OVERPASS_ENDPOINTS){try{const r=await timed(ep,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8',Accept:'application/json','User-Agent':'GhostLane/1.8.0 camera-mesh'},body:`data=${encodeURIComponent(q)}`},15000);if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();const nodes=(d.elements||[]).map(normOsm).filter(Boolean);if(nodes.length)return{nodes,source:'OpenStreetMap / Overpass'};throw new Error('zero OKC nodes')}catch(e){failures.push(`${ep}: ${e.name==='AbortError'?'timeout':e.message}`)}}throw new Error(`Overpass unavailable (${failures.join(' | ')})`)}
function meters(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function merge(groups){const out=[];for(const g of groups)for(const n of g.nodes||[]){const hit=out.find(x=>meters(x,n)<=18);if(hit){hit.sources=[...new Set([...(hit.sources||[hit.source]),n.source])];if(!hit.headingKnown&&n.headingKnown){hit.heading=n.heading;hit.headingKnown=true}if(hit.category!=='alpr'&&n.category==='alpr')Object.assign(hit,n,{sources:hit.sources});continue}out.push({...n,sources:[n.source]})}return out}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','public, max-age=0, s-maxage=1800, stale-while-revalidate=86400');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method!=='GET')return res.status(405).json({error:'GET required.'});const groups=[],failures=[],results=await Promise.allSettled([fetchDeflock(),fetchOverpass()]);for(const result of results){if(result.status==='fulfilled')groups.push(result.value);else failures.push(result.reason?.message||'Camera source failed')}if(!groups.length)return res.status(502).json({error:'All public camera sources are temporarily unavailable.',failures});const nodes=merge(groups),categories=nodes.reduce((a,n)=>(a[n.category]=(a[n.category]||0)+1,a),{}),hasCurrentAlprSource=groups.some(group=>(group.nodes||[]).some(node=>node.category==='alpr'));return res.status(200).json({nodes,count:nodes.length,categories,region:'Oklahoma City metro',sources:groups.map(g=>({name:g.source,count:g.nodes.length})),partial:!hasCurrentAlprSource,failures,generatedAt:new Date().toISOString()})};
